// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpapfqcqirtjwhogbtbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwYXBmcWNxaXJ0andob2didGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTIyMTIsImV4cCI6MjA3MTA4ODIxMn0.J5qWa7cMcp5Hz_xILNW68zn8ACprg4CtoZVvDnIhIFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});